[package]
name = "madarska_metoda"
version = "0.1.0"
authors = ["Hrvoje <hrvoje.lesar1@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]