[package]
name = "madarska_metoda"
version = "0.1.2"
authors = ["Hrvoje <hrvoje.lesar1@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "madarska_metoda"
path = "src/lib.rs"

[dependencies]